log:
  log_dir: 'log'
  chkpt_dir: 'chkpt'


arcface:
  chkpt_path: '/SHARED/Arcface.pth'
  vector_size: 256

data:
  dataset_dir: '/SHARED/vggface2/train-preprocessed'
  valset_dir: '/SHARED/vggface2/test-tiny'

model:
  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  batch_size: 16

  num_workers: 1
  grad_clip: 0.0